name: Build dev MacOS x64 binary
on:
  workflow_dispatch:

jobs:
  build-dev-mac-x64:
    name: Build dev x64 MacOS binary
    runs-on: macos-latest
    env:
      BUILD_ARCH: x64
      BUILD_LOGLEVEL: verbose
    steps:
      - uses: actions/checkout@v3
      - run: npm install --production --ignore-scripts
      - run: (cd nexe && npm install --production)
      - run: (cd nexe && node build)
      - run: nexe/parpar --version
      - run: nexe/parpar -r1 -s1M -onexe/test.par2 nexe/parpar
      - run: xz -9e --x86 --lzma2 nexe/parpar -c > parpar.xz
      - uses: actions/upload-artifact@v3
        with:
          path: ./parpar.xz
          name: parpar-${{ github.ref_name }}-macos-x64.xz
          retention-days: 5
